# Generated by Django 5.1.4 on 2025-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprferences',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
