# Generated by Django 5.1.4 on 2025-01-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0003_alter_userprferences_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprferences',
            name='currency',
            field=models.CharField(default='USD', max_length=255),
        ),
    ]
